---
title: "Customer Personality Analysis"
description: |
  A short description of the post.
author:
  - name: Alex Wainwright
    url: https://github.com/alexwhitelockw
date: 2022-02-17
output:
  distill::distill_article:
    self_contained: false
draft: True
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Libraries ---------------------------

library(brms)
library(data.table)
library(ggplot2)

# Read Data ---------------------------

customer_personality <-
  fread("data/marketing_campaign.csv")

customer_personality <-
  customer_personality[, .(ID,
                           Education,
                           Marital_Status,
                           Income,
                           Kidhome,
                           Teenhome,
                           NumDealsPurchases)]

```

# Explore Data

```{r}

customer_personality[, Income := ifelse(is.na(Income), median(Income, na.rm = T), Income)]

melt(
  customer_personality[,.(ID, Education, Marital_Status)], 
  id.vars = "ID",
  variable.name = "Demographic"
) |>
  ggplot(aes(x = value, y = ..count..)) +
  geom_bar(
    fill = "#591C21"
  ) +
  labs(
    x = NULL,
    y = "Count"
  ) +
  coord_flip() +
  facet_wrap(~Demographic, scales = "free_y") +
  theme_bw() +
  theme(
    panel.background = element_rect(
      fill = "#F2F2F2"
    ),
    plot.background = element_rect(
      fill = "#F2F2F2"
    )
  )

```

```{r}

ggplot(customer_personality, aes(x = log(Income))) +
  geom_density(
    alpha = .5,
    colour = "#044040",
    fill = "#044040",
    size = 1.25
  ) +
  scale_x_continuous(
    breaks = 8:20*1,
    sec.axis = sec_axis(trans = ~ exp(.))
  ) +
  theme_bw()

```

```{r}
table(customer_personality$Kidhome)
table(customer_personality$Teenhome)
```

